"use client";

import { useState } from "react";
import Link from "next/link";
import { ChevronDown } from "lucide-react";
import { ScriptrLogo } from "@/components/ui/logo";
import { cn } from "@/lib/utils";

const FAQS = [
  {
    category: "Getting Started",
    items: [
      {
        q: "What is Scriptr?",
        a: "Scriptr is an AI-powered YouTube toolkit. It finds outlier videos in any niche (videos getting 2–10x more views than the channel average), writes full video scripts, tracks competitors, helps with research, and generates thumbnail concepts — all in one place.",
      },
      {
        q: "How do I get started?",
        a: "Sign up, head to the Outlier Detector and enter any YouTube channel handle. Find a video with a high outlier score, then click 'Write Script' to generate a full script based on it. The whole process takes under 12 minutes.",
      },
      {
        q: "Do I need a YouTube channel to use Scriptr?",
        a: "No — you can use it to research any niche, analyze competitors, and generate scripts even before you start a channel.",
      },
    ],
  },
  {
    category: "Features",
    items: [
      {
        q: "What is the Outlier Detector?",
        a: "It analyzes a YouTube channel's video library and uses the median view count as a baseline. Videos performing 1.5x, 3x, or 10x above that median are flagged as outliers — these are the proven topics worth creating your own version of.",
      },
      {
        q: "How does the Voice Profile work?",
        a: "In Settings → Voice Profile, you describe your writing style, paste an example script, and list phrases to avoid. Every script Scriptr generates will then match your tone and voice instead of sounding generic.",
      },
      {
        q: "What's the Idea Generator?",
        a: "Enter your niche and Scriptr generates 50 proven video ideas tailored to your style. Each idea comes with a hook, the unique angle, format recommendation, and view potential. Click 'Script it' on any idea to jump straight into the script writer.",
      },
      {
        q: "How does competitor tracking work?",
        a: "Add any YouTube channel to your competitors list. Scriptr automatically fetches their latest videos and outlier scores every 6 hours so you can see what's trending in your niche without manually checking.",
      },
      {
        q: "What file types does the Research assistant support?",
        a: "YouTube video URLs (auto-transcribed), any webpage or article URL (scraped), and plain text. You can add multiple sources and then ask questions or generate script context from all of them combined.",
      },
      {
        q: "How does the AI Thumbnail Generator work?",
        a: "Describe your video and Scriptr generates 4 thumbnail concept descriptions using Claude. Pick one and generate the actual image using FLUX Schnell (16:9 format, high quality). Download and use directly.",
      },
    ],
  },
  {
    category: "Pricing & Trial",
    items: [
      {
        q: "What's included in the $5 trial?",
        a: "Full access to every feature for 7 days — outlier detection, script writing, idea generation, competitor tracking, research assistant, and thumbnail studio. After 7 days, it automatically renews at $29/month or $249/year depending on which plan you chose.",
      },
      {
        q: "What are the free plan limits?",
        a: "The free plan includes 10 outlier searches, 5 scripts, and 2 tracked competitors per month. Idea generation also counts toward your outlier search limit.",
      },
      {
        q: "Can I cancel anytime?",
        a: "Yes. Go to Settings and click 'Manage billing' to cancel through the Stripe portal. You keep Pro access until the end of your billing period.",
      },
      {
        q: "What's the difference between monthly and yearly?",
        a: "Monthly is $29/month. Yearly is $249/year — that's $20.75/month, saving you $99 compared to monthly billing.",
      },
      {
        q: "Is there a refund policy?",
        a: "The $5 trial fee is non-refundable. If you cancel your subscription within the first billing cycle after the trial ends, contact us and we'll review it case by case.",
      },
    ],
  },
  {
    category: "Technical",
    items: [
      {
        q: "Which AI model powers the scripts?",
        a: "Scripts and ideas are generated by Claude Sonnet (Anthropic). Thumbnails are generated by FLUX Schnell via Replicate. Both are state-of-the-art models for their respective tasks.",
      },
      {
        q: "How accurate is the outlier detection?",
        a: "It uses the median view count (not the average) as the baseline, which prevents one viral video from skewing the results. The scoring is based on real YouTube data pulled from the YouTube Data API v3.",
      },
      {
        q: "Is my data private?",
        a: "Yes. Your scripts, voice profile, and research sources are stored privately and only accessible to your account. We do not use your content to train AI models.",
      },
    ],
  },
];

function FAQItem({ q, a }: { q: string; a: string }) {
  const [open, setOpen] = useState(false);
  return (
    <div
      className="rounded-2xl overflow-hidden transition-all duration-200"
      style={{ background: "rgba(255,255,255,0.03)", border: "1px solid rgba(255,255,255,0.07)" }}
    >
      <button
        onClick={() => setOpen(!open)}
        className="w-full flex items-center justify-between px-5 py-4 text-left gap-4 cursor-pointer hover:bg-white/[0.02] transition-colors"
      >
        <span className="text-sm font-medium text-white/85">{q}</span>
        <ChevronDown
          className={cn("h-4 w-4 text-white/30 flex-shrink-0 transition-transform duration-200", open && "rotate-180")}
        />
      </button>
      {open && (
        <div className="px-5 pb-4 text-sm text-white/50 leading-relaxed border-t border-white/5 pt-3">
          {a}
        </div>
      )}
    </div>
  );
}

export default function FAQPage() {
  return (
    <div className="min-h-screen" style={{ background: "#08080f" }}>
      {/* Header */}
      <header className="border-b border-white/5 px-6 py-4 flex items-center justify-between">
        <Link href="/dashboard" className="flex items-center gap-2">
          <ScriptrLogo />
        </Link>
        <Link
          href="/dashboard"
          className="text-sm text-white/50 hover:text-white/80 transition-colors cursor-pointer"
        >
          Back to app →
        </Link>
      </header>

      <div className="max-w-3xl mx-auto px-6 py-16 space-y-12 animate-fade-up">
        <div className="text-center space-y-3">
          <h1 className="text-4xl font-bold gradient-text">Frequently Asked Questions</h1>
          <p className="text-white/40">Everything you need to know about Scriptr.</p>
        </div>

        {FAQS.map((section) => (
          <div key={section.category} className="space-y-3">
            <p className="text-xs font-semibold uppercase tracking-widest text-white/25 px-1">
              {section.category}
            </p>
            {section.items.map((item) => (
              <FAQItem key={item.q} q={item.q} a={item.a} />
            ))}
          </div>
        ))}

        <div
          className="rounded-2xl p-8 text-center space-y-4"
          style={{ background: "rgba(124,58,237,0.08)", border: "1px solid rgba(124,58,237,0.2)" }}
        >
          <p className="text-white/70 font-medium">Still have questions?</p>
          <p className="text-white/40 text-sm">
            Reach out at{" "}
            <a href="mailto:support@scriptr.ai" className="text-violet-400 hover:text-violet-300 transition-colors cursor-pointer">
              support@scriptr.ai
            </a>
          </p>
        </div>
      </div>
    </div>
  );
}
